'use client';

import Link from 'next/link';
import { ArrowRight, Bell, ChevronRight, ClipboardList, Heart, MapPin, Package, ShieldCheck, UserRound } from 'lucide-react';
import { useState } from 'react';

const nav = [['Overview', '/account', UserRound], ['Orders', '/account/orders', Package], ['Saved addresses', '/account/addresses', MapPin], ['Wishlist', '/account/wishlist', Heart], ['Consultations', '/account/consultations', ClipboardList], ['Settings', '/account/settings', Bell]] as const;

export function AccountDashboard({ section = 'overview' }: { section?: string }) {
  const [notice, setNotice] = useState('');
  const active = section === 'overview' ? 'Overview' : section.replace('-', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
  return <div className="page-shell pb-24 pt-12 sm:pt-20"><div className="grid gap-10 lg:grid-cols-[220px_1fr]"><aside><p className="eyebrow">Your HITUDE</p><h1 className="mt-3 font-display text-4xl">Account</h1><nav className="mt-8 flex gap-2 overflow-x-auto lg:flex-col" aria-label="Account navigation">{nav.map(([label, href, Icon]) => <Link key={href} href={href} className={`flex min-h-11 shrink-0 items-center gap-3 rounded-xl px-3 text-sm transition ${active === label ? 'bg-cream font-semibold' : 'text-ink/55 hover:bg-cream'}`}><Icon size={16} />{label}</Link>)}</nav><button className="button-quiet mt-8 hidden lg:block" onClick={() => setNotice('You have been securely signed out on this device.')}>Sign out</button>{notice && <p className="mt-4 text-xs leading-5 text-moss">{notice}</p>}</aside><section className="min-w-0"><div className="flex flex-col justify-between gap-4 border-b border-line pb-6 sm:flex-row sm:items-end"><div><p className="eyebrow">{active}</p><h2 className="mt-2 font-display text-4xl sm:text-5xl">Good to have you here.</h2></div><span className="flex items-center gap-2 text-xs text-moss"><ShieldCheck size={14} /> Account protected</span></div>{section === 'overview' ? <Overview /> : <SectionContent section={section} />}</section></div></div>;
}

function Overview() { return <div className="mt-8 grid gap-5 sm:grid-cols-2"><div className="rounded-3xl bg-cream p-6 sm:p-8"><p className="eyebrow">Latest order</p><h3 className="mt-12 font-display text-2xl">No orders yet.</h3><p className="mt-2 text-sm leading-6 text-ink/55">Your considered choices will appear here, along with tracking and invoice details.</p><Link href="/shop" className="button button-primary mt-6">Explore the edit <ArrowRight size={16} /></Link></div><div className="rounded-3xl border border-line p-6 sm:p-8"><p className="eyebrow">Your details</p><div className="mt-10 space-y-4 text-sm"><div className="flex items-center justify-between"><span className="text-ink/50">Email</span><span>Not set</span></div><div className="flex items-center justify-between"><span className="text-ink/50">Phone</span><span>Not set</span></div><div className="flex items-center justify-between"><span className="text-ink/50">Addresses</span><span>0 saved</span></div></div><Link href="/account/settings" className="button-quiet mt-8 inline-flex items-center gap-2">Manage details <ChevronRight size={15} /></Link></div><div className="rounded-3xl border border-line p-6 sm:col-span-2 sm:p-8"><div className="flex items-center justify-between"><div><p className="eyebrow">Consultation history</p><h3 className="mt-3 font-display text-2xl">Questions are part of the journey.</h3></div><Link href="/account/consultations" className="button-quiet hidden items-center gap-2 sm:flex">View history <ChevronRight size={15} /></Link></div><p className="mt-4 max-w-lg text-sm leading-6 text-ink/55">No consultation requests yet. If you’d like a person to talk through your options, we’re here.</p><Link href="/consultation" className="button button-secondary mt-6">Request a consultation</Link></div></div>; }

function SectionContent({ section }: { section: string }) { const title = section === 'orders' ? 'Order history' : section === 'addresses' ? 'Saved addresses' : section === 'wishlist' ? 'Wishlist' : section === 'consultations' ? 'Consultation requests' : 'Account settings'; return <div className="mt-8 rounded-3xl border border-dashed border-line p-8 sm:p-12"><p className="eyebrow">{title}</p><h3 className="mt-4 font-display text-3xl">Nothing here just yet.</h3><p className="mt-3 max-w-md text-sm leading-6 text-ink/55">This area is ready for your account data. Connect it to the authenticated API to manage {section.replace('-', ' ')} securely.</p>{section === 'settings' && <div className="mt-8 grid max-w-xl gap-3"><Link className="rounded-2xl border border-line p-4 text-sm font-semibold hover:bg-cream" href="/forgot-password">Change password <span className="float-right">→</span></Link><button className="rounded-2xl border border-line p-4 text-left text-sm font-semibold hover:bg-[#f7e4df]">Request account deletion <span className="float-right">→</span></button></div>}{section === 'orders' && <Link href="/shop" className="button button-primary mt-8">Shop gummies <ArrowRight size={16} /></Link>}</div>; }

