'use client';

import Link from 'next/link';
import { ArrowRight, Eye, EyeOff, LoaderCircle, LockKeyhole } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { api } from '@/lib/api-client';

export function AuthForm({ mode }: { mode: 'login' | 'register' }) {
  const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(''); const data = new FormData(event.currentTarget); try { if (mode === 'login') { await api.login({ email: String(data.get('email')), password: String(data.get('password')) }); const target = new URLSearchParams(window.location.search).get('next') ?? '/account'; window.location.assign(target.startsWith('/') ? target : '/account'); } else { await api.register({ email: String(data.get('email')), password: String(data.get('password')), firstName: String(data.get('firstName')), consent: data.get('consent') === 'yes' }); window.location.assign('/verify-email'); } } catch (error) { setMessage(error instanceof Error ? error.message : 'We could not complete that request. Please try again.'); } finally { setLoading(false); } }
  return <div className="w-full max-w-md"><div className="mb-10 flex items-center gap-2 text-xs text-moss"><LockKeyhole size={14} /> Secure, discreet account access</div><p className="eyebrow">{mode === 'login' ? 'Welcome back' : 'Start here'}</p><h1 className="mt-4 font-display text-5xl">{mode === 'login' ? 'Good to see you.' : 'Make room for intention.'}</h1><p className="mt-5 text-sm leading-6 text-ink/60">{mode === 'login' ? 'Sign in to see your orders, saved profiles, and consultation history.' : 'Create your account to check out faster and keep your HITUDE details in one place.'}</p><form className="mt-9 space-y-5" onSubmit={submit}>{mode === 'register' && <div><label className="field-label" htmlFor="firstName">First name</label><input required id="firstName" name="firstName" autoComplete="given-name" className="input" /></div>}<div><label className="field-label" htmlFor="auth-email">Email address</label><input required id="auth-email" name="email" type="email" autoComplete="email" className="input" /></div><div><div className="flex items-center justify-between"><label className="field-label" htmlFor="auth-password">Password</label>{mode === 'login' && <Link className="text-xs text-ink/50 underline underline-offset-2" href="/forgot-password">Forgot password?</Link>}</div><div className="relative"><input required minLength={8} id="auth-password" name="password" type={showPassword ? 'text' : 'password'} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} className="input pr-12" /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} className="absolute right-1 top-1 h-10 w-10 text-ink/45" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></div>{mode === 'register' && <label className="flex items-start gap-3 text-xs leading-5 text-ink/60"><input required name="consent" value="yes" type="checkbox" className="mt-1 h-4 w-4 accent-moss" />I agree to the HITUDE privacy policy and terms of service, and consent to account communications.</label>}{message && <p role="status" className={`rounded-xl p-3 text-sm ${message.includes('could not') ? 'bg-[#f7e4df] text-vermillion' : 'bg-[#dfe6df] text-moss'}`}>{message}</p>}<button disabled={loading} className="button button-primary w-full" type="submit">{loading && <LoaderCircle size={16} className="animate-spin" />}{mode === 'login' ? 'Sign in' : 'Create account'} {!loading && <ArrowRight size={16} />}</button></form>{mode === 'login' ? <p className="mt-8 text-center text-sm text-ink/55">New here? <Link className="font-semibold text-ink underline underline-offset-4" href="/register">Create an account</Link></p> : <p className="mt-8 text-center text-sm text-ink/55">Already have an account? <Link className="font-semibold text-ink underline underline-offset-4" href="/login">Sign in</Link></p>}</div>;
}
