'use client';

import Link from 'next/link';
import { ArrowLeft, ArrowRight, Minus, Plus, Trash2 } from 'lucide-react';
import { useCart } from './cart-context';
import { ProductVisual } from './product-visual';
import { formatINR } from '@/lib/utils';

export function CartPageClient() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  const shipping = subtotal >= 999 || subtotal === 0 ? 0 : 79;
  const total = subtotal + shipping;
  return <div className="page-shell pb-24 pt-12 sm:pt-20"><Link href="/shop" className="inline-flex items-center gap-2 text-xs font-semibold text-ink/55"><ArrowLeft size={15} /> Continue shopping</Link><div className="mt-10 grid gap-12 lg:grid-cols-[1.3fr_.7fr]"><div><div className="flex items-end justify-between border-b border-line pb-5"><div><p className="eyebrow">Your edit</p><h1 className="mt-2 font-display text-5xl">Shopping cart</h1></div><p className="text-sm text-ink/50">{items.reduce((sum, item) => sum + item.quantity, 0)} items</p></div>{items.length === 0 ? <div className="rounded-3xl border border-dashed border-line p-10 text-center sm:p-16"><h2 className="font-display text-3xl">Your cart is waiting.</h2><p className="mt-3 text-sm leading-6 text-ink/55">Choose a profile to get started.</p><Link href="/shop" className="button button-primary mt-6">Explore gummies <ArrowRight size={16} /></Link></div> : <div className="divide-y divide-line">{items.map((item) => <div className="flex gap-4 py-6 sm:gap-6" key={`${item.product.id}-${item.pack}`}><ProductVisual product={item.product} compact /><div className="min-w-0 flex-1"><div className="flex justify-between gap-4"><div><p className="eyebrow">{item.product.name}</p><h2 className="mt-1 font-display text-2xl">{item.pack} gummies</h2></div><p className="font-medium">{formatINR(item.packPrice * item.quantity)}</p></div><div className="mt-5 flex items-center justify-between"><div className="quantity-stepper"><button aria-label="Decrease quantity" onClick={() => updateQuantity(`${item.product.id}-${item.pack}`, item.quantity - 1)}><Minus size={13} /></button><span>{item.quantity}</span><button aria-label="Increase quantity" onClick={() => updateQuantity(`${item.product.id}-${item.pack}`, item.quantity + 1)}><Plus size={13} /></button></div><button className="flex min-h-11 items-center gap-2 text-xs font-semibold text-ink/45 hover:text-vermillion" onClick={() => removeItem(`${item.product.id}-${item.pack}`)}><Trash2 size={15} /> Remove</button></div></div></div>)}</div>}</div><aside className="h-fit rounded-3xl bg-cream p-6 sm:p-8"><p className="eyebrow">Order summary</p><div className="mt-8 space-y-4 border-b border-ink/10 pb-6 text-sm"><div className="flex justify-between"><span className="text-ink/55">Subtotal</span><span>{formatINR(subtotal)}</span></div><div className="flex justify-between"><span className="text-ink/55">Shipping estimate</span><span>{shipping === 0 ? 'Free' : formatINR(shipping)}</span></div></div><div className="flex justify-between pt-5 font-semibold"><span>Total</span><span>{formatINR(total)}</span></div><p className="mt-4 text-xs leading-5 text-ink/50">Taxes, pincode availability, and any required verification are confirmed at checkout.</p><Link href={items.length ? '/checkout' : '/shop'} className="button button-primary mt-7 w-full">Continue to checkout <ArrowRight size={16} /></Link></aside></div></div>;
}

