import Link from 'next/link';
import { ArrowRight, Check, Leaf, ShieldCheck } from 'lucide-react';
import { SimpleForm } from './simple-form';

export function ContentPage({ type }: { type: 'story' | 'safety' | 'consultation' | 'contact' | 'shipping' | 'returns' | 'privacy' | 'terms' | 'age' }) {
  if (type === 'consultation' || type === 'contact') return <div className="page-shell pb-24 pt-16 sm:pt-24"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="eyebrow">{type === 'consultation' ? 'A person, when you want one' : 'We’re listening'}</p><h1 className="mt-5 font-display text-5xl leading-[.98] sm:text-7xl">{type === 'consultation' ? <>Let’s make it<br /><span className="text-vermillion">clear.</span></> : <>Say hello.<br /><span className="text-vermillion">We mean it.</span></>}</h1><p className="mt-7 max-w-md text-[17px] leading-8 text-ink/62">{type === 'consultation' ? 'Have a question about a profile, an ingredient, or the process? Share what’s on your mind and a member of the team can follow up.' : 'For order support, product questions, or anything else that belongs in a conversation.'}</p><div className="mt-10 rounded-3xl bg-cream p-6"><p className="eyebrow">What to expect</p><div className="mt-5 space-y-4 text-sm text-ink/65"><p className="flex gap-3"><Check size={16} className="mt-0.5 shrink-0 text-moss" />A clear, human response</p><p className="flex gap-3"><Check size={16} className="mt-0.5 shrink-0 text-moss" />No pressure to purchase</p><p className="flex gap-3"><Check size={16} className="mt-0.5 shrink-0 text-moss" />Your details handled with care</p></div></div></div><div className="rounded-3xl border border-line p-6 sm:p-10"><SimpleForm kind={type} /></div></div></div>;
  const content = {
    story: { eyebrow: 'The HITUDE point of view', title: <>Wellness can be<br /><span className="text-vermillion">more intentional.</span></>, intro: 'We started HITUDE with a simple belief: the products we bring into our lives deserve more thought, not more noise.', body: ['Our work lives at the intersection of Ayurveda, contemporary formulation, and a more honest kind of commerce. We make products that are easy to understand, discreet to receive, and considered from the first click to the last gummy.', 'We are still learning. That is why we build education into the experience, keep our language responsible, and make room for questions. A ritual should feel personal — never pressured.'] },
    safety: { eyebrow: 'Read before you ritual', title: <>The most important<br /><span className="text-vermillion">part is context.</span></>, intro: 'HITUDE products are intended for adults 18 and over. Availability, eligibility, and verification requirements may vary by location.', body: ['Please read the full product label, serving information, and local guidance before ordering. Do not drive or operate machinery after use, and do not combine with alcohol or other substances unless a qualified professional has advised you otherwise.', 'If you are pregnant, breastfeeding, taking medication, managing a condition, or unsure whether this product is appropriate for you, speak with a qualified healthcare professional before use. HITUDE products are not intended to diagnose, treat, cure, or prevent disease.'] },
    shipping: { eyebrow: 'Policy / shipping', title: <>The details<br /><span className="text-vermillion">after checkout.</span></>, intro: 'Delivery is location-dependent. We show the latest available information at checkout after you enter your pincode.', body: ['Orders may require age or eligibility verification before dispatch. Packaging is discreet. Delivery windows, service areas, shipping fees, and supported payment methods are editable operational data and must be confirmed before launch.', 'For order-specific questions, contact the support team with your order number.'] },
    returns: { eyebrow: 'Policy / returns & refunds', title: <>A clear policy<br /><span className="text-vermillion">builds trust.</span></>, intro: 'Our returns and refund terms are being finalized with the operations and compliance teams.', body: ['This page is a CMS-ready placeholder. Before launch, publish the approved eligibility window, unopened-product requirements, exceptions, refund timing, cancellation rules, and support contact details.', 'Please do not rely on this draft as a final policy.'] },
    privacy: { eyebrow: 'Policy / privacy', title: <>Your information<br /><span className="text-vermillion">is yours.</span></>, intro: 'We use information to provide the service you request, keep accounts secure, and improve the experience with consent.', body: ['This page is a CMS-ready placeholder for the approved privacy notice. Before launch, document data categories, processing purposes, retention periods, processors, user rights, cookies, cross-border transfers, deletion requests, and contact details.', 'Sensitive prescription and private medical data must be stored securely in the primary database or an approved secure file store — never in Redis caches.'] },
    terms: { eyebrow: 'Policy / terms of service', title: <>Know the<br /><span className="text-vermillion">agreement.</span></>, intro: 'These terms are being prepared for review by HITUDE’s legal and compliance owners.', body: ['This page is a CMS-ready placeholder. Publish approved purchase terms, age eligibility, payment, delivery, intellectual property, limitations, dispute process, and support details before launch.', 'The storefront is designed to make the relationship clear at every step.'] },
    age: { eyebrow: 'Policy / age & eligibility', title: <>Good choices<br /><span className="text-vermillion">start here.</span></>, intro: 'HITUDE products are intended for adults 18 and over. We may ask for age, eligibility, or prescription verification depending on your location and the product.', body: ['By using the site, you confirm that you meet the applicable age requirement and will provide accurate information if a verification step is requested.', 'If you are not eligible, please do not attempt to place an order. Questions are welcome through our consultation flow.'] },
  }[type];
  return <div className="page-shell pb-24 pt-16 sm:pt-24"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-24"><div><p className="eyebrow">{content.eyebrow}</p><h1 className="mt-5 font-display text-5xl leading-[.98] sm:text-7xl">{content.title}</h1><p className="mt-7 max-w-md text-[17px] leading-8 text-ink/62">{content.intro}</p><Link href={type === 'safety' || type === 'age' ? '/consultation' : '/shop'} className="button button-secondary mt-8">{type === 'safety' || type === 'age' ? 'Ask a question' : 'Explore the shop'} <ArrowRight size={16} /></Link></div><article className="max-w-2xl border-t border-line pt-8 sm:pt-10"><div className="flex items-center gap-3 rounded-2xl bg-cream p-4 text-sm text-ink/65"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-paper text-moss"><ShieldCheck size={18} /></span>Education and policies should support an informed choice.</div><div className="mt-10 space-y-8 text-[17px] leading-8 text-ink/65">{content.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="mt-12 border-t border-line pt-7"><p className="eyebrow">Need more context?</p><Link href="/blog" className="mt-3 inline-flex items-center gap-2 text-sm font-semibold">Read the journal <ArrowRight size={15} /></Link></div></article></div></div>;
}

