'use client';

import { ArrowRight, Check } from 'lucide-react';
import { FormEvent, useState } from 'react';

export function SimpleForm({ kind }: { kind: 'forgot' | 'reset' | 'consultation' | 'contact' }) {
  const [done, setDone] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setDone(true); }
  if (done) return <div className="rounded-2xl bg-[#dfe6df] p-5 text-sm leading-6 text-moss"><Check size={18} className="mb-3" />{kind === 'forgot' && 'If an account exists for that email, a secure reset link is on its way.'}{kind === 'reset' && 'Your password has been reset. You can now sign in securely.'}{kind === 'consultation' && 'Your request is in. A member of the team will follow up with next steps.'}{kind === 'contact' && 'Message received. We’ll be in touch as soon as we can.'}</div>;
  if (kind === 'consultation') return <form onSubmit={submit} className="space-y-5"><div><label className="field-label" htmlFor="consult-name">Your name</label><input required id="consult-name" className="input" /></div><div><label className="field-label" htmlFor="consult-email">Email address</label><input required id="consult-email" type="email" className="input" /></div><div><label className="field-label" htmlFor="consult-question">What would you like to ask?</label><textarea required id="consult-question" className="input min-h-32 py-3" /></div><div><label className="field-label" htmlFor="consult-time">Preferred contact time</label><select id="consult-time" className="input"><option>Morning</option><option>Afternoon</option><option>Evening</option></select></div><label className="flex items-start gap-3 text-xs leading-5 text-ink/60"><input required type="checkbox" className="mt-1 h-4 w-4 accent-moss" />I consent to HITUDE using these details to respond to my request.</label><button className="button button-primary" type="submit">Send request <ArrowRight size={16} /></button></form>;
  if (kind === 'contact') return <form onSubmit={submit} className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><div><label className="field-label" htmlFor="contact-name">Name</label><input required id="contact-name" className="input" /></div><div><label className="field-label" htmlFor="contact-email">Email address</label><input required id="contact-email" type="email" className="input" /></div></div><div><label className="field-label" htmlFor="contact-topic">Topic</label><select id="contact-topic" className="input"><option>Order support</option><option>Product question</option><option>Consultation</option><option>Other</option></select></div><div><label className="field-label" htmlFor="contact-message">Message</label><textarea required id="contact-message" className="input min-h-36 py-3" /></div><button className="button button-primary" type="submit">Send message <ArrowRight size={16} /></button></form>;
  return <form onSubmit={submit} className="space-y-5">{kind === 'forgot' ? <div><label className="field-label" htmlFor="forgot-email">Email address</label><input required id="forgot-email" type="email" className="input" /></div> : <><div><label className="field-label" htmlFor="reset-password">New password</label><input required minLength={8} id="reset-password" type="password" className="input" /></div><div><label className="field-label" htmlFor="reset-confirm">Confirm new password</label><input required minLength={8} id="reset-confirm" type="password" className="input" /></div></>}<button className="button button-primary w-full" type="submit">{kind === 'forgot' ? 'Email reset link' : 'Reset password'} <ArrowRight size={16} /></button></form>;
}

