import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Clock3 } from 'lucide-react';
import { notFound } from 'next/navigation';
import { posts } from '@/lib/product-data';
export function generateStaticParams() { return posts.map((post) => ({ slug: post.slug })); }
export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> { const post = posts.find((item) => item.slug === params.slug); return post ? { title: post.title, description: post.excerpt, alternates: { canonical: `/blog/${post.slug}` }, openGraph: { title: post.title, description: post.excerpt, type: 'article' } } : {}; }
export default function BlogArticlePage({ params }: { params: { slug: string } }) { const post = posts.find((item) => item.slug === params.slug); if (!post) notFound(); const article = { '@context': 'https://schema.org', '@type': 'Article', headline: post.title, description: post.excerpt, author: { '@type': 'Organization', name: 'HITUDE Editorial' }, publisher: { '@type': 'Organization', name: 'HITUDE' } }; return <div className="page-shell pb-24 pt-10 sm:pt-16"><Link href="/blog" className="inline-flex items-center gap-2 text-xs font-semibold text-ink/55"><ArrowLeft size={15} /> Back to journal</Link><article className="mx-auto mt-12 max-w-3xl"><div className="text-center"><p className="eyebrow">{post.category}</p><h1 className="mt-5 font-display text-5xl leading-[.98] tracking-[-.04em] sm:text-7xl">{post.title}</h1><p className="mx-auto mt-6 max-w-xl text-[17px] leading-8 text-ink/62">{post.excerpt}</p><div className="mt-5 flex items-center justify-center gap-2 text-xs text-ink/45"><Clock3 size={14} /> {post.readTime} · {post.date}</div></div><div className="mt-14 overflow-hidden rounded-3xl bg-[#d7e1d5] p-8 sm:p-16"><div className="flex min-h-48 items-center justify-center rounded-2xl border border-ink/10"><span className="font-display text-7xl text-ink/15">H / note</span></div></div><div className="prose-hitude mx-auto mt-14 max-w-2xl"><p>There is a lot of language around wellness. The useful kind usually begins with a quieter question: what exactly am I choosing?</p><h2>Start with the label</h2><p>Look for the ingredient list, serving information, and any location-specific guidance. A clear label does not remove the need for personal context — it gives you a better place to begin.</p><h2>Make room for your own context</h2><p>Your experience is shaped by more than a product. Your schedule, health, other substances, and the guidance of qualified professionals all matter. If you’re unsure, asking a question is a responsible next step.</p><div className="my-10 rounded-2xl bg-cream p-5 text-sm leading-6 text-ink/65">Editorial note: this article is educational, not medical advice. Verify final copy and claims with HITUDE’s compliance owner before publishing.</div><p>We believe a wellness brand should make space for nuance. That’s what this journal is for: practical information, clear language, and fewer promises.</p></div></article><div className="mx-auto mt-20 max-w-2xl border-t border-line pt-7"><Link href="/consultation" className="button button-secondary">Have a question? Talk to us <ArrowRight size={16} /></Link></div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(article) }} /></div>; }

